### ISSUE TITLE
Compile error with :is() selector

### ISSUE THREAD

**Issue by Knovour** [saulhardman/postcss-hover-media-feature#8]
Source
```
:is(button, [role="button"]):hover {
	background-color: transparent;
}
```

Run `postcss btn.css -o out.css`

Result
```
:is(button {
	background-color: transparent;
}@media (hover: hover) {[role="button"]):hover {
	background-color: transparent;
}
}
```

Expected
```
@media (hover: hover) {
  :is(button, [role="button"]):hover {
    background-color: transparent;
  }
}
```

It works ok when :hover is inside
```
:is(button:hover, [role="button"]:hover) {
	background-color: transparent;
}
```

[Example](https://codesandbox.io/s/postcss-forked-eejeb)

**Comment by saulhardman** [comment]
Hey @Knovour, thanks for the bug report :+1: I'm going to take a look at this now and get back to you ASAP. Thanks for your patience 😊

**Comment by saulhardman** [comment]
Hi again @Knovour, I've just pushed a [new release (v1.0.1)](https://www.npmjs.com/package/postcss-hover-media-feature) – if you could test it and confirm that the fix has worked I'd very much appreciate it. Thanks in advance 🙂

**Comment by Knovour** [comment]
All working now, thank you!
